spring:
  data:
    mongodb:
      uri: mongodb://root:root@127.0.0.1:27017/test?authSource=admin
      #uri等同于下面的配置
      #database:test
      #host:192.168.65.174
      #port:27017
      #username:fox
      #password:fox
      #authentication-database:admin